[package]
name = "day16"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "16_part1"
path = "src/16_part1.rs"

[[bin]]
name = "16_part2"
path = "src/16_part2.rs"

[dependencies]
